In [46]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# 1.Numpy Array

In [47]:
import numpy as np

In [48]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
a[0]

1

In [50]:
a[2:5]

array([3, 4, 5])

In [51]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [52]:
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

### INDEX ติด - ใช้บ่อยมาก !!!!!!!

In [53]:
a[-2]

9

In [54]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [55]:
a[-5:-1]

array([6, 7, 8, 9])

In [56]:
np.size(a)

10

In [57]:
np.shape(a)

(10,)

In [58]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
a[0,0]

1

In [60]:
a[1,:]

array([4, 5, 6])

In [61]:
a[:,-1]

array([3, 6, 9])

In [62]:
a[:,-1] = 0
a

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

คำสั่ง Size สั่งนับทั้งหมด แถว หลัก ได้!!!

In [63]:
a = np.array ([[1,2,3],
               [4,5,6],
               [7,8,9],
               [10,11,12]])

np.size(a)

12

In [64]:
np.ndim(a)

2

In [65]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [66]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

# 2.Special Type of Matrix

In [67]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [68]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [69]:
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [70]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [71]:
c*d

array([[8., 0.],
       [0., 8.]])

In [72]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [73]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [74]:
np.empty([5,5])

array([[0.39112905, 0.72141094, 0.90724038, 0.4758676 , 0.        ],
       [0.73866907, 0.12358873, 0.47876429, 0.00929772, 0.        ],
       [0.27361999, 0.33676601, 0.37509048, 0.32443928, 0.        ],
       [0.31044427, 0.3796574 , 0.55425133, 0.90771954, 1.        ],
       [0.76173266, 0.0112233 , 0.00703738, 0.06629275, 1.        ]])

# 3.Random

In [75]:
import numpy as np
np.random.rand()

0.44469325332613363

In [76]:
np.random.randint(5)

2

In [77]:
np.random .seed (100)
np.random.rand()

0.5434049417909654

In [78]:
np.random.rand(5,5)

array([[0.27836939, 0.42451759, 0.84477613, 0.00471886, 0.12156912],
       [0.67074908, 0.82585276, 0.13670659, 0.57509333, 0.89132195],
       [0.20920212, 0.18532822, 0.10837689, 0.21969749, 0.97862378],
       [0.81168315, 0.17194101, 0.81622475, 0.27407375, 0.43170418],
       [0.94002982, 0.81764938, 0.33611195, 0.17541045, 0.37283205]])

In [79]:
np.round(np.random.rand(5,5))

array([[0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 0., 1.],
       [1., 0., 0., 1., 1.]])

## EX.1

In [80]:
np.round(np.random.rand(5,5)*1000)

array([[885., 360., 599., 355., 340.],
       [178., 238.,  45., 505., 376.],
       [593., 630., 143., 934., 946.],
       [602., 388., 363., 204., 277.],
       [247., 174., 967., 957., 598.]])

In [81]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([6, 7, 5, 8, 4])

### replace = False คือ สุ่มให้เลขไม่ซ้ำกัน

In [82]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([8, 9, 7, 5, 6])

บรรทัดแรก สุ่มขัอมูลออกมา 1000 แถว 5 คอลั่ม / บรรทัด 2 : เลือกจาก 0-999 เลือกมา 3 แถว

In [83]:
np_matrix = np.random.rand(1000,5)
idx_choose = np.random.choice(1000,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.92105197, 0.30339253, 0.3140533 , 0.04803149, 0.32883516],
       [0.72949434, 0.41264077, 0.19083605, 0.70601952, 0.24063282],
       [0.89570142, 0.2084805 , 0.06319644, 0.23942167, 0.78019925]])

# Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.

In [84]:
np_matrix = np.random.rand(10,5)
last_c = np.round(np_matrix[:,4])
np_matrix[:,4] = last_c
np_matrix

array([[0.3542077 , 0.72250667, 0.08158589, 0.41544511, 0.        ],
       [0.48571888, 0.26623067, 0.18385521, 0.86661561, 0.        ],
       [0.49240024, 0.26391841, 0.35857047, 0.01532433, 0.        ],
       [0.30381344, 0.4842303 , 0.19439123, 0.46720065, 0.        ],
       [0.39112905, 0.72141094, 0.90724038, 0.4758676 , 0.        ],
       [0.73866907, 0.12358873, 0.47876429, 0.00929772, 0.        ],
       [0.27361999, 0.33676601, 0.37509048, 0.32443928, 0.        ],
       [0.31044427, 0.3796574 , 0.55425133, 0.90771954, 1.        ],
       [0.76173266, 0.0112233 , 0.00703738, 0.06629275, 1.        ],
       [0.79490744, 0.69887961, 0.12476746, 0.6642765 , 0.        ]])

In [85]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 5,  5,  7,  0,  7],
       [10, 10,  3,  9,  7],
       [ 2,  5,  7,  8,  1],
       [ 3,  6,  7,  1,  1],
       [ 8,  6,  0,  7,  0]])

In [86]:
i,j = np.where(np_matrix == 2)

In [87]:
i

array([2])

In [88]:
j

array([0])

# Ex 3. Why we cannot use this index ? Please fix it !!

In [89]:
idx = [0,1,2,3,4]
np_matrix[idx,:]

array([[ 5,  5,  7,  0,  7],
       [10, 10,  3,  9,  7],
       [ 2,  5,  7,  8,  1],
       [ 3,  6,  7,  1,  1],
       [ 8,  6,  0,  7,  0]])

In [90]:
np_matrix

array([[ 5,  5,  7,  0,  7],
       [10, 10,  3,  9,  7],
       [ 2,  5,  7,  8,  1],
       [ 3,  6,  7,  1,  1],
       [ 8,  6,  0,  7,  0]])

[1,2],0 คือ ลบ "แถว" ที่ 1กับ2 / [1,2],1 คือ ลบ "หลัก" ที่ 1กับ2

In [91]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[5, 5, 7, 0, 7],
       [3, 6, 7, 1, 1],
       [8, 6, 0, 7, 0]])

In [92]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[8, 2, 4, 5, 7],
       [2, 4, 1, 2, 7],
       [3, 9, 8, 0, 4],
       [5, 5, 3, 3, 9],
       [0, 6, 8, 5, 5]])

In [93]:
result = (np_matrix == 2)
result

array([[False,  True, False, False, False],
       [ True, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [94]:
np_matrix[result] = 99
np_matrix

array([[ 8, 99,  4,  5,  7],
       [99,  4,  1, 99,  7],
       [ 3,  9,  8,  0,  4],
       [ 5,  5,  3,  3,  9],
       [ 0,  6,  8,  5,  5]])

In [95]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[4, 2, 3, 4, 3],
       [2, 3, 4, 2, 5],
       [4, 2, 4, 3, 1],
       [2, 2, 3, 2, 5],
       [1, 1, 5, 3, 3]])

# Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
# Then, randomly create a label vector for 10 samples.  
# Finally, seperate data matrix into 2 groups
# Group 1 called train_data (label == 0)
# Group 2 called test_data (label == 1)

2.สร้าง list เป็น Vector 10 แถว
3.แบ่ง DATA Matrix เป็น 2 กลุ่ม 

Sample = แถว / Features = คอลัม!!!!

In [118]:
#4.1
data_matrix = np.random.randint(10,size = (10,5))
data_matrix

array([[5, 8, 9, 6, 5],
       [9, 3, 6, 7, 4],
       [8, 6, 8, 5, 0],
       [1, 0, 8, 0, 1],
       [7, 7, 9, 9, 6],
       [4, 7, 2, 5, 3],
       [6, 3, 8, 8, 6],
       [2, 0, 7, 3, 5],
       [8, 3, 9, 8, 4],
       [0, 5, 1, 1, 4]])

In [120]:
#4.2
label_vecter = np.random.randint(2,size = (10))
label_vecter

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [121]:
#4.3
train_data = (label_vecter == 0)
data_matrix[train_data]

array([[9, 3, 6, 7, 4],
       [8, 6, 8, 5, 0],
       [1, 0, 8, 0, 1],
       [7, 7, 9, 9, 6],
       [0, 5, 1, 1, 4]])

In [123]:
#4.4
test_data = (label_vecter == 1)
data_matrix[test_data]

array([[5, 8, 9, 6, 5],
       [4, 7, 2, 5, 3],
       [6, 3, 8, 8, 6],
       [2, 0, 7, 3, 5],
       [8, 3, 9, 8, 4]])

# 4.Important Function

In [96]:
np.max(data)

5

In [97]:
np.max(data,0)

array([4, 3, 5, 4, 5])

In [98]:
np.max(data,1)

array([4, 5, 4, 5, 5])

In [99]:
np.sum(data)

73

In [100]:
np.average(data)

2.92

In [101]:
data[0,:]

array([4, 2, 3, 4, 3])

argmax คือ ตำแหน่งไหนสูงสุด

In [102]:
np.argmax(data[0,:])

0

In [103]:
np.sort(data[0,:])

array([2, 3, 3, 4, 4])

In [104]:
np.argsort(data[0,:])

array([1, 2, 4, 0, 3])

# Ex.5 How to sort in decreasing order using np.sort


In [124]:
np.sort(data[0,:])[::-1]

array([2., 2., 2., 1., 0.])

In [105]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

linear space = ตั้งแต่เลข 5 -10 แบ่งเป็น 10 ส่วนเท่ากัน

In [106]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [107]:
data = np.round(np.random.random((5,5))*3)
data

array([[2., 2., 0., 2., 1.],
       [3., 3., 2., 2., 1.],
       [2., 0., 1., 1., 1.],
       [1., 0., 3., 2., 2.],
       [1., 2., 1., 0., 1.]])

In [108]:
data.shape

(5, 5)

In [109]:
data.reshape(1,25)

array([[2., 2., 0., 2., 1., 3., 3., 2., 2., 1., 2., 0., 1., 1., 1., 1.,
        0., 3., 2., 2., 1., 2., 1., 0., 1.]])

In [110]:
a = [[1,2],[3,4]]
a

[[1, 2], [3, 4]]

In [111]:
np.tile(a,(4,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

# Ex. 6 Extract all the numbers divisible by 3 from np_test. Note: Please use only 1 line command
np_test= np.arange(25).reshape(5,5)
np_test

In [125]:
np_test= np.arange(25).reshape(5,5)
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [126]:
np_test[np_test%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])


# Ex.7 Change diagonal element of np_test to 0. Note: Please use only 1 line command (Google it!!)
#
np_test

In [127]:
np_test[np.fill_diagonal(np_test,0)]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])